---
- name: Install Neovim
  hosts: all
  become: yes
  tasks:
    - name: Install build prerequisites
      package:
        name:
          - git
          - ninja-build
          - cmake
          - gettext
          - curl
          - unzip
        state: present

    - name: Clone Neovim repository
      git:
        repo: https://github.com/neovim/neovim.git
        dest: /tmp/neovim

    - name: Build and install Neovim
      shell: |
        cd /tmp/neovim &&
        make CMAKE_BUILD_TYPE=RelWithDebInfo
        sudo make install
      args:
        executable: /bin/bash
